package com.dc.dlsb.dao;

import com.dc.dlsb.model.OmsJzglJzxx;
import com.dc.dlsb.model.OmsJzglJzxxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsJzglJzxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int countByExample(OmsJzglJzxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int deleteByExample(OmsJzglJzxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String jzbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int insert(OmsJzglJzxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int insertSelective(OmsJzglJzxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    List<OmsJzglJzxx> selectByExample(OmsJzglJzxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    OmsJzglJzxx selectByPrimaryKey(String jzbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OmsJzglJzxx record, @Param("example") OmsJzglJzxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OmsJzglJzxx record, @Param("example") OmsJzglJzxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OmsJzglJzxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OmsJzglJzxx record);
}