package com.dc.dlsb.model;

import java.util.ArrayList;
import java.util.List;

public class DmeDrcSumJzDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public DmeDrcSumJzDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJzbhIsNull() {
            addCriterion("JZBH is null");
            return (Criteria) this;
        }

        public Criteria andJzbhIsNotNull() {
            addCriterion("JZBH is not null");
            return (Criteria) this;
        }

        public Criteria andJzbhEqualTo(String value) {
            addCriterion("JZBH =", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotEqualTo(String value) {
            addCriterion("JZBH <>", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhGreaterThan(String value) {
            addCriterion("JZBH >", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhGreaterThanOrEqualTo(String value) {
            addCriterion("JZBH >=", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLessThan(String value) {
            addCriterion("JZBH <", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLessThanOrEqualTo(String value) {
            addCriterion("JZBH <=", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLike(String value) {
            addCriterion("JZBH like", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotLike(String value) {
            addCriterion("JZBH not like", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhIn(List<String> values) {
            addCriterion("JZBH in", values, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotIn(List<String> values) {
            addCriterion("JZBH not in", values, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhBetween(String value1, String value2) {
            addCriterion("JZBH between", value1, value2, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotBetween(String value1, String value2) {
            addCriterion("JZBH not between", value1, value2, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzmcIsNull() {
            addCriterion("JZMC is null");
            return (Criteria) this;
        }

        public Criteria andJzmcIsNotNull() {
            addCriterion("JZMC is not null");
            return (Criteria) this;
        }

        public Criteria andJzmcEqualTo(String value) {
            addCriterion("JZMC =", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotEqualTo(String value) {
            addCriterion("JZMC <>", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcGreaterThan(String value) {
            addCriterion("JZMC >", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcGreaterThanOrEqualTo(String value) {
            addCriterion("JZMC >=", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLessThan(String value) {
            addCriterion("JZMC <", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLessThanOrEqualTo(String value) {
            addCriterion("JZMC <=", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLike(String value) {
            addCriterion("JZMC like", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotLike(String value) {
            addCriterion("JZMC not like", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcIn(List<String> values) {
            addCriterion("JZMC in", values, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotIn(List<String> values) {
            addCriterion("JZMC not in", values, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcBetween(String value1, String value2) {
            addCriterion("JZMC between", value1, value2, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotBetween(String value1, String value2) {
            addCriterion("JZMC not between", value1, value2, "jzmc");
            return (Criteria) this;
        }

        public Criteria andDatadatefIsNull() {
            addCriterion("DATADATEF is null");
            return (Criteria) this;
        }

        public Criteria andDatadatefIsNotNull() {
            addCriterion("DATADATEF is not null");
            return (Criteria) this;
        }

        public Criteria andDatadatefEqualTo(String value) {
            addCriterion("DATADATEF =", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotEqualTo(String value) {
            addCriterion("DATADATEF <>", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefGreaterThan(String value) {
            addCriterion("DATADATEF >", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefGreaterThanOrEqualTo(String value) {
            addCriterion("DATADATEF >=", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLessThan(String value) {
            addCriterion("DATADATEF <", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLessThanOrEqualTo(String value) {
            addCriterion("DATADATEF <=", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLike(String value) {
            addCriterion("DATADATEF like", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotLike(String value) {
            addCriterion("DATADATEF not like", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefIn(List<String> values) {
            addCriterion("DATADATEF in", values, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotIn(List<String> values) {
            addCriterion("DATADATEF not in", values, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefBetween(String value1, String value2) {
            addCriterion("DATADATEF between", value1, value2, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotBetween(String value1, String value2) {
            addCriterion("DATADATEF not between", value1, value2, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatanumIsNull() {
            addCriterion("DATANUM is null");
            return (Criteria) this;
        }

        public Criteria andDatanumIsNotNull() {
            addCriterion("DATANUM is not null");
            return (Criteria) this;
        }

        public Criteria andDatanumEqualTo(String value) {
            addCriterion("DATANUM =", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumNotEqualTo(String value) {
            addCriterion("DATANUM <>", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumGreaterThan(String value) {
            addCriterion("DATANUM >", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumGreaterThanOrEqualTo(String value) {
            addCriterion("DATANUM >=", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumLessThan(String value) {
            addCriterion("DATANUM <", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumLessThanOrEqualTo(String value) {
            addCriterion("DATANUM <=", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumLike(String value) {
            addCriterion("DATANUM like", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumNotLike(String value) {
            addCriterion("DATANUM not like", value, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumIn(List<String> values) {
            addCriterion("DATANUM in", values, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumNotIn(List<String> values) {
            addCriterion("DATANUM not in", values, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumBetween(String value1, String value2) {
            addCriterion("DATANUM between", value1, value2, "datanum");
            return (Criteria) this;
        }

        public Criteria andDatanumNotBetween(String value1, String value2) {
            addCriterion("DATANUM not between", value1, value2, "datanum");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNull() {
            addCriterion("JLSJ is null");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNotNull() {
            addCriterion("JLSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJlsjEqualTo(String value) {
            addCriterion("JLSJ =", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotEqualTo(String value) {
            addCriterion("JLSJ <>", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThan(String value) {
            addCriterion("JLSJ >", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThanOrEqualTo(String value) {
            addCriterion("JLSJ >=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThan(String value) {
            addCriterion("JLSJ <", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThanOrEqualTo(String value) {
            addCriterion("JLSJ <=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLike(String value) {
            addCriterion("JLSJ like", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotLike(String value) {
            addCriterion("JLSJ not like", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjIn(List<String> values) {
            addCriterion("JLSJ in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotIn(List<String> values) {
            addCriterion("JLSJ not in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjBetween(String value1, String value2) {
            addCriterion("JLSJ between", value1, value2, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotBetween(String value1, String value2) {
            addCriterion("JLSJ not between", value1, value2, "jlsj");
            return (Criteria) this;
        }

        public Criteria andOiIdfIsNull() {
            addCriterion("OI_IDF is null");
            return (Criteria) this;
        }

        public Criteria andOiIdfIsNotNull() {
            addCriterion("OI_IDF is not null");
            return (Criteria) this;
        }

        public Criteria andOiIdfEqualTo(String value) {
            addCriterion("OI_IDF =", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotEqualTo(String value) {
            addCriterion("OI_IDF <>", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfGreaterThan(String value) {
            addCriterion("OI_IDF >", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfGreaterThanOrEqualTo(String value) {
            addCriterion("OI_IDF >=", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLessThan(String value) {
            addCriterion("OI_IDF <", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLessThanOrEqualTo(String value) {
            addCriterion("OI_IDF <=", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLike(String value) {
            addCriterion("OI_IDF like", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotLike(String value) {
            addCriterion("OI_IDF not like", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfIn(List<String> values) {
            addCriterion("OI_IDF in", values, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotIn(List<String> values) {
            addCriterion("OI_IDF not in", values, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfBetween(String value1, String value2) {
            addCriterion("OI_IDF between", value1, value2, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotBetween(String value1, String value2) {
            addCriterion("OI_IDF not between", value1, value2, "oiIdf");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}