package com.dc.dlsb.model;

import java.util.ArrayList;
import java.util.List;

public class DmeDrcDdrbCfgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public DmeDrcDdrbCfgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdIsNull() {
            addCriterion("CZPXT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdIsNotNull() {
            addCriterion("CZPXT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdEqualTo(String value) {
            addCriterion("CZPXT_ID =", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdNotEqualTo(String value) {
            addCriterion("CZPXT_ID <>", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdGreaterThan(String value) {
            addCriterion("CZPXT_ID >", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdGreaterThanOrEqualTo(String value) {
            addCriterion("CZPXT_ID >=", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdLessThan(String value) {
            addCriterion("CZPXT_ID <", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdLessThanOrEqualTo(String value) {
            addCriterion("CZPXT_ID <=", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdLike(String value) {
            addCriterion("CZPXT_ID like", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdNotLike(String value) {
            addCriterion("CZPXT_ID not like", value, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdIn(List<String> values) {
            addCriterion("CZPXT_ID in", values, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdNotIn(List<String> values) {
            addCriterion("CZPXT_ID not in", values, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdBetween(String value1, String value2) {
            addCriterion("CZPXT_ID between", value1, value2, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andCzpxtIdNotBetween(String value1, String value2) {
            addCriterion("CZPXT_ID not between", value1, value2, "czpxtId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdIsNull() {
            addCriterion("DLLDB_ID is null");
            return (Criteria) this;
        }

        public Criteria andDlldbIdIsNotNull() {
            addCriterion("DLLDB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDlldbIdEqualTo(String value) {
            addCriterion("DLLDB_ID =", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdNotEqualTo(String value) {
            addCriterion("DLLDB_ID <>", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdGreaterThan(String value) {
            addCriterion("DLLDB_ID >", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdGreaterThanOrEqualTo(String value) {
            addCriterion("DLLDB_ID >=", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdLessThan(String value) {
            addCriterion("DLLDB_ID <", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdLessThanOrEqualTo(String value) {
            addCriterion("DLLDB_ID <=", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdLike(String value) {
            addCriterion("DLLDB_ID like", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdNotLike(String value) {
            addCriterion("DLLDB_ID not like", value, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdIn(List<String> values) {
            addCriterion("DLLDB_ID in", values, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdNotIn(List<String> values) {
            addCriterion("DLLDB_ID not in", values, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdBetween(String value1, String value2) {
            addCriterion("DLLDB_ID between", value1, value2, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andDlldbIdNotBetween(String value1, String value2) {
            addCriterion("DLLDB_ID not between", value1, value2, "dlldbId");
            return (Criteria) this;
        }

        public Criteria andFhycIdIsNull() {
            addCriterion("FHYC_ID is null");
            return (Criteria) this;
        }

        public Criteria andFhycIdIsNotNull() {
            addCriterion("FHYC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFhycIdEqualTo(String value) {
            addCriterion("FHYC_ID =", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdNotEqualTo(String value) {
            addCriterion("FHYC_ID <>", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdGreaterThan(String value) {
            addCriterion("FHYC_ID >", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdGreaterThanOrEqualTo(String value) {
            addCriterion("FHYC_ID >=", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdLessThan(String value) {
            addCriterion("FHYC_ID <", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdLessThanOrEqualTo(String value) {
            addCriterion("FHYC_ID <=", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdLike(String value) {
            addCriterion("FHYC_ID like", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdNotLike(String value) {
            addCriterion("FHYC_ID not like", value, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdIn(List<String> values) {
            addCriterion("FHYC_ID in", values, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdNotIn(List<String> values) {
            addCriterion("FHYC_ID not in", values, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdBetween(String value1, String value2) {
            addCriterion("FHYC_ID between", value1, value2, "fhycId");
            return (Criteria) this;
        }

        public Criteria andFhycIdNotBetween(String value1, String value2) {
            addCriterion("FHYC_ID not between", value1, value2, "fhycId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdIsNull() {
            addCriterion("WDS_NEW_ID is null");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdIsNotNull() {
            addCriterion("WDS_NEW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdEqualTo(String value) {
            addCriterion("WDS_NEW_ID =", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdNotEqualTo(String value) {
            addCriterion("WDS_NEW_ID <>", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdGreaterThan(String value) {
            addCriterion("WDS_NEW_ID >", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdGreaterThanOrEqualTo(String value) {
            addCriterion("WDS_NEW_ID >=", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdLessThan(String value) {
            addCriterion("WDS_NEW_ID <", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdLessThanOrEqualTo(String value) {
            addCriterion("WDS_NEW_ID <=", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdLike(String value) {
            addCriterion("WDS_NEW_ID like", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdNotLike(String value) {
            addCriterion("WDS_NEW_ID not like", value, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdIn(List<String> values) {
            addCriterion("WDS_NEW_ID in", values, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdNotIn(List<String> values) {
            addCriterion("WDS_NEW_ID not in", values, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdBetween(String value1, String value2) {
            addCriterion("WDS_NEW_ID between", value1, value2, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andWdsNewIdNotBetween(String value1, String value2) {
            addCriterion("WDS_NEW_ID not between", value1, value2, "wdsNewId");
            return (Criteria) this;
        }

        public Criteria andScadaIdIsNull() {
            addCriterion("SCADA_ID is null");
            return (Criteria) this;
        }

        public Criteria andScadaIdIsNotNull() {
            addCriterion("SCADA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andScadaIdEqualTo(String value) {
            addCriterion("SCADA_ID =", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdNotEqualTo(String value) {
            addCriterion("SCADA_ID <>", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdGreaterThan(String value) {
            addCriterion("SCADA_ID >", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdGreaterThanOrEqualTo(String value) {
            addCriterion("SCADA_ID >=", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdLessThan(String value) {
            addCriterion("SCADA_ID <", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdLessThanOrEqualTo(String value) {
            addCriterion("SCADA_ID <=", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdLike(String value) {
            addCriterion("SCADA_ID like", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdNotLike(String value) {
            addCriterion("SCADA_ID not like", value, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdIn(List<String> values) {
            addCriterion("SCADA_ID in", values, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdNotIn(List<String> values) {
            addCriterion("SCADA_ID not in", values, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdBetween(String value1, String value2) {
            addCriterion("SCADA_ID between", value1, value2, "scadaId");
            return (Criteria) this;
        }

        public Criteria andScadaIdNotBetween(String value1, String value2) {
            addCriterion("SCADA_ID not between", value1, value2, "scadaId");
            return (Criteria) this;
        }

        public Criteria andOmsIdIsNull() {
            addCriterion("OMS_ID is null");
            return (Criteria) this;
        }

        public Criteria andOmsIdIsNotNull() {
            addCriterion("OMS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOmsIdEqualTo(String value) {
            addCriterion("OMS_ID =", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdNotEqualTo(String value) {
            addCriterion("OMS_ID <>", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdGreaterThan(String value) {
            addCriterion("OMS_ID >", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdGreaterThanOrEqualTo(String value) {
            addCriterion("OMS_ID >=", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdLessThan(String value) {
            addCriterion("OMS_ID <", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdLessThanOrEqualTo(String value) {
            addCriterion("OMS_ID <=", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdLike(String value) {
            addCriterion("OMS_ID like", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdNotLike(String value) {
            addCriterion("OMS_ID not like", value, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdIn(List<String> values) {
            addCriterion("OMS_ID in", values, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdNotIn(List<String> values) {
            addCriterion("OMS_ID not in", values, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdBetween(String value1, String value2) {
            addCriterion("OMS_ID between", value1, value2, "omsId");
            return (Criteria) this;
        }

        public Criteria andOmsIdNotBetween(String value1, String value2) {
            addCriterion("OMS_ID not between", value1, value2, "omsId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIsNull() {
            addCriterion("CFG_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIsNotNull() {
            addCriterion("CFG_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCfgTypeEqualTo(String value) {
            addCriterion("CFG_TYPE =", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotEqualTo(String value) {
            addCriterion("CFG_TYPE <>", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeGreaterThan(String value) {
            addCriterion("CFG_TYPE >", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CFG_TYPE >=", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLessThan(String value) {
            addCriterion("CFG_TYPE <", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLessThanOrEqualTo(String value) {
            addCriterion("CFG_TYPE <=", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLike(String value) {
            addCriterion("CFG_TYPE like", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotLike(String value) {
            addCriterion("CFG_TYPE not like", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIn(List<String> values) {
            addCriterion("CFG_TYPE in", values, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotIn(List<String> values) {
            addCriterion("CFG_TYPE not in", values, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeBetween(String value1, String value2) {
            addCriterion("CFG_TYPE between", value1, value2, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotBetween(String value1, String value2) {
            addCriterion("CFG_TYPE not between", value1, value2, "cfgType");
            return (Criteria) this;
        }

        public Criteria andMqNewIdIsNull() {
            addCriterion("MQ_NEW_ID is null");
            return (Criteria) this;
        }

        public Criteria andMqNewIdIsNotNull() {
            addCriterion("MQ_NEW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMqNewIdEqualTo(String value) {
            addCriterion("MQ_NEW_ID =", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdNotEqualTo(String value) {
            addCriterion("MQ_NEW_ID <>", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdGreaterThan(String value) {
            addCriterion("MQ_NEW_ID >", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdGreaterThanOrEqualTo(String value) {
            addCriterion("MQ_NEW_ID >=", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdLessThan(String value) {
            addCriterion("MQ_NEW_ID <", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdLessThanOrEqualTo(String value) {
            addCriterion("MQ_NEW_ID <=", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdLike(String value) {
            addCriterion("MQ_NEW_ID like", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdNotLike(String value) {
            addCriterion("MQ_NEW_ID not like", value, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdIn(List<String> values) {
            addCriterion("MQ_NEW_ID in", values, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdNotIn(List<String> values) {
            addCriterion("MQ_NEW_ID not in", values, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdBetween(String value1, String value2) {
            addCriterion("MQ_NEW_ID between", value1, value2, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andMqNewIdNotBetween(String value1, String value2) {
            addCriterion("MQ_NEW_ID not between", value1, value2, "mqNewId");
            return (Criteria) this;
        }

        public Criteria andPxIsNull() {
            addCriterion("PX is null");
            return (Criteria) this;
        }

        public Criteria andPxIsNotNull() {
            addCriterion("PX is not null");
            return (Criteria) this;
        }

        public Criteria andPxEqualTo(Long value) {
            addCriterion("PX =", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotEqualTo(Long value) {
            addCriterion("PX <>", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxGreaterThan(Long value) {
            addCriterion("PX >", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxGreaterThanOrEqualTo(Long value) {
            addCriterion("PX >=", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxLessThan(Long value) {
            addCriterion("PX <", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxLessThanOrEqualTo(Long value) {
            addCriterion("PX <=", value, "px");
            return (Criteria) this;
        }

        public Criteria andPxIn(List<Long> values) {
            addCriterion("PX in", values, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotIn(List<Long> values) {
            addCriterion("PX not in", values, "px");
            return (Criteria) this;
        }

        public Criteria andPxBetween(Long value1, Long value2) {
            addCriterion("PX between", value1, value2, "px");
            return (Criteria) this;
        }

        public Criteria andPxNotBetween(Long value1, Long value2) {
            addCriterion("PX not between", value1, value2, "px");
            return (Criteria) this;
        }

        public Criteria andIsStopIsNull() {
            addCriterion("IS_STOP is null");
            return (Criteria) this;
        }

        public Criteria andIsStopIsNotNull() {
            addCriterion("IS_STOP is not null");
            return (Criteria) this;
        }

        public Criteria andIsStopEqualTo(Short value) {
            addCriterion("IS_STOP =", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotEqualTo(Short value) {
            addCriterion("IS_STOP <>", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopGreaterThan(Short value) {
            addCriterion("IS_STOP >", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_STOP >=", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopLessThan(Short value) {
            addCriterion("IS_STOP <", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopLessThanOrEqualTo(Short value) {
            addCriterion("IS_STOP <=", value, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopIn(List<Short> values) {
            addCriterion("IS_STOP in", values, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotIn(List<Short> values) {
            addCriterion("IS_STOP not in", values, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopBetween(Short value1, Short value2) {
            addCriterion("IS_STOP between", value1, value2, "isStop");
            return (Criteria) this;
        }

        public Criteria andIsStopNotBetween(Short value1, Short value2) {
            addCriterion("IS_STOP not between", value1, value2, "isStop");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidIsNull() {
            addCriterion("WDS_RTUID is null");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidIsNotNull() {
            addCriterion("WDS_RTUID is not null");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidEqualTo(String value) {
            addCriterion("WDS_RTUID =", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidNotEqualTo(String value) {
            addCriterion("WDS_RTUID <>", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidGreaterThan(String value) {
            addCriterion("WDS_RTUID >", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidGreaterThanOrEqualTo(String value) {
            addCriterion("WDS_RTUID >=", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidLessThan(String value) {
            addCriterion("WDS_RTUID <", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidLessThanOrEqualTo(String value) {
            addCriterion("WDS_RTUID <=", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidLike(String value) {
            addCriterion("WDS_RTUID like", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidNotLike(String value) {
            addCriterion("WDS_RTUID not like", value, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidIn(List<String> values) {
            addCriterion("WDS_RTUID in", values, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidNotIn(List<String> values) {
            addCriterion("WDS_RTUID not in", values, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidBetween(String value1, String value2) {
            addCriterion("WDS_RTUID between", value1, value2, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andWdsRtuidNotBetween(String value1, String value2) {
            addCriterion("WDS_RTUID not between", value1, value2, "wdsRtuid");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdIsNull() {
            addCriterion("QJNY_POWER_ID is null");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdIsNotNull() {
            addCriterion("QJNY_POWER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdEqualTo(String value) {
            addCriterion("QJNY_POWER_ID =", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdNotEqualTo(String value) {
            addCriterion("QJNY_POWER_ID <>", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdGreaterThan(String value) {
            addCriterion("QJNY_POWER_ID >", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdGreaterThanOrEqualTo(String value) {
            addCriterion("QJNY_POWER_ID >=", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdLessThan(String value) {
            addCriterion("QJNY_POWER_ID <", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdLessThanOrEqualTo(String value) {
            addCriterion("QJNY_POWER_ID <=", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdLike(String value) {
            addCriterion("QJNY_POWER_ID like", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdNotLike(String value) {
            addCriterion("QJNY_POWER_ID not like", value, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdIn(List<String> values) {
            addCriterion("QJNY_POWER_ID in", values, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdNotIn(List<String> values) {
            addCriterion("QJNY_POWER_ID not in", values, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdBetween(String value1, String value2) {
            addCriterion("QJNY_POWER_ID between", value1, value2, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andQjnyPowerIdNotBetween(String value1, String value2) {
            addCriterion("QJNY_POWER_ID not between", value1, value2, "qjnyPowerId");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidIsNull() {
            addCriterion("OMS_ORGID is null");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidIsNotNull() {
            addCriterion("OMS_ORGID is not null");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidEqualTo(String value) {
            addCriterion("OMS_ORGID =", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidNotEqualTo(String value) {
            addCriterion("OMS_ORGID <>", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidGreaterThan(String value) {
            addCriterion("OMS_ORGID >", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("OMS_ORGID >=", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidLessThan(String value) {
            addCriterion("OMS_ORGID <", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidLessThanOrEqualTo(String value) {
            addCriterion("OMS_ORGID <=", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidLike(String value) {
            addCriterion("OMS_ORGID like", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidNotLike(String value) {
            addCriterion("OMS_ORGID not like", value, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidIn(List<String> values) {
            addCriterion("OMS_ORGID in", values, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidNotIn(List<String> values) {
            addCriterion("OMS_ORGID not in", values, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidBetween(String value1, String value2) {
            addCriterion("OMS_ORGID between", value1, value2, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsOrgidNotBetween(String value1, String value2) {
            addCriterion("OMS_ORGID not between", value1, value2, "omsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidIsNull() {
            addCriterion("SB_OMS_ORGID is null");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidIsNotNull() {
            addCriterion("SB_OMS_ORGID is not null");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidEqualTo(String value) {
            addCriterion("SB_OMS_ORGID =", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidNotEqualTo(String value) {
            addCriterion("SB_OMS_ORGID <>", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidGreaterThan(String value) {
            addCriterion("SB_OMS_ORGID >", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("SB_OMS_ORGID >=", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidLessThan(String value) {
            addCriterion("SB_OMS_ORGID <", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidLessThanOrEqualTo(String value) {
            addCriterion("SB_OMS_ORGID <=", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidLike(String value) {
            addCriterion("SB_OMS_ORGID like", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidNotLike(String value) {
            addCriterion("SB_OMS_ORGID not like", value, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidIn(List<String> values) {
            addCriterion("SB_OMS_ORGID in", values, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidNotIn(List<String> values) {
            addCriterion("SB_OMS_ORGID not in", values, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidBetween(String value1, String value2) {
            addCriterion("SB_OMS_ORGID between", value1, value2, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andSbOmsOrgidNotBetween(String value1, String value2) {
            addCriterion("SB_OMS_ORGID not between", value1, value2, "sbOmsOrgid");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdIsNull() {
            addCriterion("OMS_DC_ID is null");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdIsNotNull() {
            addCriterion("OMS_DC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdEqualTo(String value) {
            addCriterion("OMS_DC_ID =", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdNotEqualTo(String value) {
            addCriterion("OMS_DC_ID <>", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdGreaterThan(String value) {
            addCriterion("OMS_DC_ID >", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdGreaterThanOrEqualTo(String value) {
            addCriterion("OMS_DC_ID >=", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdLessThan(String value) {
            addCriterion("OMS_DC_ID <", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdLessThanOrEqualTo(String value) {
            addCriterion("OMS_DC_ID <=", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdLike(String value) {
            addCriterion("OMS_DC_ID like", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdNotLike(String value) {
            addCriterion("OMS_DC_ID not like", value, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdIn(List<String> values) {
            addCriterion("OMS_DC_ID in", values, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdNotIn(List<String> values) {
            addCriterion("OMS_DC_ID not in", values, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdBetween(String value1, String value2) {
            addCriterion("OMS_DC_ID between", value1, value2, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andOmsDcIdNotBetween(String value1, String value2) {
            addCriterion("OMS_DC_ID not between", value1, value2, "omsDcId");
            return (Criteria) this;
        }

        public Criteria andDlsbPxIsNull() {
            addCriterion("DLSB_PX is null");
            return (Criteria) this;
        }

        public Criteria andDlsbPxIsNotNull() {
            addCriterion("DLSB_PX is not null");
            return (Criteria) this;
        }

        public Criteria andDlsbPxEqualTo(Long value) {
            addCriterion("DLSB_PX =", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxNotEqualTo(Long value) {
            addCriterion("DLSB_PX <>", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxGreaterThan(Long value) {
            addCriterion("DLSB_PX >", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxGreaterThanOrEqualTo(Long value) {
            addCriterion("DLSB_PX >=", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxLessThan(Long value) {
            addCriterion("DLSB_PX <", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxLessThanOrEqualTo(Long value) {
            addCriterion("DLSB_PX <=", value, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxIn(List<Long> values) {
            addCriterion("DLSB_PX in", values, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxNotIn(List<Long> values) {
            addCriterion("DLSB_PX not in", values, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxBetween(Long value1, Long value2) {
            addCriterion("DLSB_PX between", value1, value2, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andDlsbPxNotBetween(Long value1, Long value2) {
            addCriterion("DLSB_PX not between", value1, value2, "dlsbPx");
            return (Criteria) this;
        }

        public Criteria andTjIdIsNull() {
            addCriterion("TJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andTjIdIsNotNull() {
            addCriterion("TJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTjIdEqualTo(String value) {
            addCriterion("TJ_ID =", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotEqualTo(String value) {
            addCriterion("TJ_ID <>", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThan(String value) {
            addCriterion("TJ_ID >", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdGreaterThanOrEqualTo(String value) {
            addCriterion("TJ_ID >=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThan(String value) {
            addCriterion("TJ_ID <", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLessThanOrEqualTo(String value) {
            addCriterion("TJ_ID <=", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdLike(String value) {
            addCriterion("TJ_ID like", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotLike(String value) {
            addCriterion("TJ_ID not like", value, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdIn(List<String> values) {
            addCriterion("TJ_ID in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotIn(List<String> values) {
            addCriterion("TJ_ID not in", values, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdBetween(String value1, String value2) {
            addCriterion("TJ_ID between", value1, value2, "tjId");
            return (Criteria) this;
        }

        public Criteria andTjIdNotBetween(String value1, String value2) {
            addCriterion("TJ_ID not between", value1, value2, "tjId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}