package com.dc.dlsb.model;

import java.io.Serializable;

public class DmeDrcSumFgpData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.OI_IDF
     *
     * @mbggenerated
     */
    private String oiIdf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.OI_NAME
     *
     * @mbggenerated
     */
    private String oiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.OI_TYPE
     *
     * @mbggenerated
     */
    private String oiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.DATA_TYPE
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.DATADATEF
     *
     * @mbggenerated
     */
    private String datadatef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.ABASEDATA
     *
     * @mbggenerated
     */
    private String abasedata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMFGPDATA2.JLSJ
     *
     * @mbggenerated
     */
    private String jlsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.OI_IDF
     *
     * @return the value of SUMFGPDATA2.OI_IDF
     *
     * @mbggenerated
     */
    public String getOiIdf() {
        return oiIdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.OI_IDF
     *
     * @param oiIdf the value for SUMFGPDATA2.OI_IDF
     *
     * @mbggenerated
     */
    public void setOiIdf(String oiIdf) {
        this.oiIdf = oiIdf == null ? null : oiIdf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.OI_NAME
     *
     * @return the value of SUMFGPDATA2.OI_NAME
     *
     * @mbggenerated
     */
    public String getOiName() {
        return oiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.OI_NAME
     *
     * @param oiName the value for SUMFGPDATA2.OI_NAME
     *
     * @mbggenerated
     */
    public void setOiName(String oiName) {
        this.oiName = oiName == null ? null : oiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.OI_TYPE
     *
     * @return the value of SUMFGPDATA2.OI_TYPE
     *
     * @mbggenerated
     */
    public String getOiType() {
        return oiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.OI_TYPE
     *
     * @param oiType the value for SUMFGPDATA2.OI_TYPE
     *
     * @mbggenerated
     */
    public void setOiType(String oiType) {
        this.oiType = oiType == null ? null : oiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.DATA_TYPE
     *
     * @return the value of SUMFGPDATA2.DATA_TYPE
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.DATA_TYPE
     *
     * @param dataType the value for SUMFGPDATA2.DATA_TYPE
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.DATADATEF
     *
     * @return the value of SUMFGPDATA2.DATADATEF
     *
     * @mbggenerated
     */
    public String getDatadatef() {
        return datadatef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.DATADATEF
     *
     * @param datadatef the value for SUMFGPDATA2.DATADATEF
     *
     * @mbggenerated
     */
    public void setDatadatef(String datadatef) {
        this.datadatef = datadatef == null ? null : datadatef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.ABASEDATA
     *
     * @return the value of SUMFGPDATA2.ABASEDATA
     *
     * @mbggenerated
     */
    public String getAbasedata() {
        return abasedata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.ABASEDATA
     *
     * @param abasedata the value for SUMFGPDATA2.ABASEDATA
     *
     * @mbggenerated
     */
    public void setAbasedata(String abasedata) {
        this.abasedata = abasedata == null ? null : abasedata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMFGPDATA2.JLSJ
     *
     * @return the value of SUMFGPDATA2.JLSJ
     *
     * @mbggenerated
     */
    public String getJlsj() {
        return jlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMFGPDATA2.JLSJ
     *
     * @param jlsj the value for SUMFGPDATA2.JLSJ
     *
     * @mbggenerated
     */
    public void setJlsj(String jlsj) {
        this.jlsj = jlsj == null ? null : jlsj.trim();
    }
}