package com.dc.dlsb.model;

import java.io.Serializable;

public class DmeDrcDdrbCfg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.CZPXT_ID
     *
     * @mbggenerated
     */
    private String czpxtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.DLLDB_ID
     *
     * @mbggenerated
     */
    private String dlldbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.FHYC_ID
     *
     * @mbggenerated
     */
    private String fhycId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.WDS_NEW_ID
     *
     * @mbggenerated
     */
    private String wdsNewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.SCADA_ID
     *
     * @mbggenerated
     */
    private String scadaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.OMS_ID
     *
     * @mbggenerated
     */
    private String omsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.CFG_TYPE
     *
     * @mbggenerated
     */
    private String cfgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.MQ_NEW_ID
     *
     * @mbggenerated
     */
    private String mqNewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.PX
     *
     * @mbggenerated
     */
    private Long px;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.IS_STOP
     *
     * @mbggenerated
     */
    private Short isStop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.WDS_RTUID
     *
     * @mbggenerated
     */
    private String wdsRtuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.QJNY_POWER_ID
     *
     * @mbggenerated
     */
    private String qjnyPowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.OMS_ORGID
     *
     * @mbggenerated
     */
    private String omsOrgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.SB_OMS_ORGID
     *
     * @mbggenerated
     */
    private String sbOmsOrgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.OMS_DC_ID
     *
     * @mbggenerated
     */
    private String omsDcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.DLSB_PX
     *
     * @mbggenerated
     */
    private Long dlsbPx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DME_DRC_DDRB_CFG_W.TJ_ID
     *
     * @mbggenerated
     */
    private String tjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DME_DRC_DDRB_CFG_W
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.ID
     *
     * @param id the value for DME_DRC_DDRB_CFG_W.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.CZPXT_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.CZPXT_ID
     *
     * @mbggenerated
     */
    public String getCzpxtId() {
        return czpxtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.CZPXT_ID
     *
     * @param czpxtId the value for DME_DRC_DDRB_CFG_W.CZPXT_ID
     *
     * @mbggenerated
     */
    public void setCzpxtId(String czpxtId) {
        this.czpxtId = czpxtId == null ? null : czpxtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.DLLDB_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.DLLDB_ID
     *
     * @mbggenerated
     */
    public String getDlldbId() {
        return dlldbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.DLLDB_ID
     *
     * @param dlldbId the value for DME_DRC_DDRB_CFG_W.DLLDB_ID
     *
     * @mbggenerated
     */
    public void setDlldbId(String dlldbId) {
        this.dlldbId = dlldbId == null ? null : dlldbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.FHYC_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.FHYC_ID
     *
     * @mbggenerated
     */
    public String getFhycId() {
        return fhycId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.FHYC_ID
     *
     * @param fhycId the value for DME_DRC_DDRB_CFG_W.FHYC_ID
     *
     * @mbggenerated
     */
    public void setFhycId(String fhycId) {
        this.fhycId = fhycId == null ? null : fhycId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.WDS_NEW_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.WDS_NEW_ID
     *
     * @mbggenerated
     */
    public String getWdsNewId() {
        return wdsNewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.WDS_NEW_ID
     *
     * @param wdsNewId the value for DME_DRC_DDRB_CFG_W.WDS_NEW_ID
     *
     * @mbggenerated
     */
    public void setWdsNewId(String wdsNewId) {
        this.wdsNewId = wdsNewId == null ? null : wdsNewId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.SCADA_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.SCADA_ID
     *
     * @mbggenerated
     */
    public String getScadaId() {
        return scadaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.SCADA_ID
     *
     * @param scadaId the value for DME_DRC_DDRB_CFG_W.SCADA_ID
     *
     * @mbggenerated
     */
    public void setScadaId(String scadaId) {
        this.scadaId = scadaId == null ? null : scadaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.OMS_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.OMS_ID
     *
     * @mbggenerated
     */
    public String getOmsId() {
        return omsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.OMS_ID
     *
     * @param omsId the value for DME_DRC_DDRB_CFG_W.OMS_ID
     *
     * @mbggenerated
     */
    public void setOmsId(String omsId) {
        this.omsId = omsId == null ? null : omsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.NAME
     *
     * @return the value of DME_DRC_DDRB_CFG_W.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.NAME
     *
     * @param name the value for DME_DRC_DDRB_CFG_W.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.CFG_TYPE
     *
     * @return the value of DME_DRC_DDRB_CFG_W.CFG_TYPE
     *
     * @mbggenerated
     */
    public String getCfgType() {
        return cfgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.CFG_TYPE
     *
     * @param cfgType the value for DME_DRC_DDRB_CFG_W.CFG_TYPE
     *
     * @mbggenerated
     */
    public void setCfgType(String cfgType) {
        this.cfgType = cfgType == null ? null : cfgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.MQ_NEW_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.MQ_NEW_ID
     *
     * @mbggenerated
     */
    public String getMqNewId() {
        return mqNewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.MQ_NEW_ID
     *
     * @param mqNewId the value for DME_DRC_DDRB_CFG_W.MQ_NEW_ID
     *
     * @mbggenerated
     */
    public void setMqNewId(String mqNewId) {
        this.mqNewId = mqNewId == null ? null : mqNewId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.PX
     *
     * @return the value of DME_DRC_DDRB_CFG_W.PX
     *
     * @mbggenerated
     */
    public Long getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.PX
     *
     * @param px the value for DME_DRC_DDRB_CFG_W.PX
     *
     * @mbggenerated
     */
    public void setPx(Long px) {
        this.px = px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.IS_STOP
     *
     * @return the value of DME_DRC_DDRB_CFG_W.IS_STOP
     *
     * @mbggenerated
     */
    public Short getIsStop() {
        return isStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.IS_STOP
     *
     * @param isStop the value for DME_DRC_DDRB_CFG_W.IS_STOP
     *
     * @mbggenerated
     */
    public void setIsStop(Short isStop) {
        this.isStop = isStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.WDS_RTUID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.WDS_RTUID
     *
     * @mbggenerated
     */
    public String getWdsRtuid() {
        return wdsRtuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.WDS_RTUID
     *
     * @param wdsRtuid the value for DME_DRC_DDRB_CFG_W.WDS_RTUID
     *
     * @mbggenerated
     */
    public void setWdsRtuid(String wdsRtuid) {
        this.wdsRtuid = wdsRtuid == null ? null : wdsRtuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.QJNY_POWER_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.QJNY_POWER_ID
     *
     * @mbggenerated
     */
    public String getQjnyPowerId() {
        return qjnyPowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.QJNY_POWER_ID
     *
     * @param qjnyPowerId the value for DME_DRC_DDRB_CFG_W.QJNY_POWER_ID
     *
     * @mbggenerated
     */
    public void setQjnyPowerId(String qjnyPowerId) {
        this.qjnyPowerId = qjnyPowerId == null ? null : qjnyPowerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.OMS_ORGID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.OMS_ORGID
     *
     * @mbggenerated
     */
    public String getOmsOrgid() {
        return omsOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.OMS_ORGID
     *
     * @param omsOrgid the value for DME_DRC_DDRB_CFG_W.OMS_ORGID
     *
     * @mbggenerated
     */
    public void setOmsOrgid(String omsOrgid) {
        this.omsOrgid = omsOrgid == null ? null : omsOrgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.SB_OMS_ORGID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.SB_OMS_ORGID
     *
     * @mbggenerated
     */
    public String getSbOmsOrgid() {
        return sbOmsOrgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.SB_OMS_ORGID
     *
     * @param sbOmsOrgid the value for DME_DRC_DDRB_CFG_W.SB_OMS_ORGID
     *
     * @mbggenerated
     */
    public void setSbOmsOrgid(String sbOmsOrgid) {
        this.sbOmsOrgid = sbOmsOrgid == null ? null : sbOmsOrgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.OMS_DC_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.OMS_DC_ID
     *
     * @mbggenerated
     */
    public String getOmsDcId() {
        return omsDcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.OMS_DC_ID
     *
     * @param omsDcId the value for DME_DRC_DDRB_CFG_W.OMS_DC_ID
     *
     * @mbggenerated
     */
    public void setOmsDcId(String omsDcId) {
        this.omsDcId = omsDcId == null ? null : omsDcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.DLSB_PX
     *
     * @return the value of DME_DRC_DDRB_CFG_W.DLSB_PX
     *
     * @mbggenerated
     */
    public Long getDlsbPx() {
        return dlsbPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.DLSB_PX
     *
     * @param dlsbPx the value for DME_DRC_DDRB_CFG_W.DLSB_PX
     *
     * @mbggenerated
     */
    public void setDlsbPx(Long dlsbPx) {
        this.dlsbPx = dlsbPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DME_DRC_DDRB_CFG_W.TJ_ID
     *
     * @return the value of DME_DRC_DDRB_CFG_W.TJ_ID
     *
     * @mbggenerated
     */
    public String getTjId() {
        return tjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DME_DRC_DDRB_CFG_W.TJ_ID
     *
     * @param tjId the value for DME_DRC_DDRB_CFG_W.TJ_ID
     *
     * @mbggenerated
     */
    public void setTjId(String tjId) {
        this.tjId = tjId == null ? null : tjId.trim();
    }
}