package com.dc.dlsb.model;

import java.util.ArrayList;
import java.util.List;

public class DmeDrcSumFgpDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public DmeDrcSumFgpDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOiIdfIsNull() {
            addCriterion("OI_IDF is null");
            return (Criteria) this;
        }

        public Criteria andOiIdfIsNotNull() {
            addCriterion("OI_IDF is not null");
            return (Criteria) this;
        }

        public Criteria andOiIdfEqualTo(String value) {
            addCriterion("OI_IDF =", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotEqualTo(String value) {
            addCriterion("OI_IDF <>", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfGreaterThan(String value) {
            addCriterion("OI_IDF >", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfGreaterThanOrEqualTo(String value) {
            addCriterion("OI_IDF >=", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLessThan(String value) {
            addCriterion("OI_IDF <", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLessThanOrEqualTo(String value) {
            addCriterion("OI_IDF <=", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfLike(String value) {
            addCriterion("OI_IDF like", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotLike(String value) {
            addCriterion("OI_IDF not like", value, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfIn(List<String> values) {
            addCriterion("OI_IDF in", values, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotIn(List<String> values) {
            addCriterion("OI_IDF not in", values, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfBetween(String value1, String value2) {
            addCriterion("OI_IDF between", value1, value2, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiIdfNotBetween(String value1, String value2) {
            addCriterion("OI_IDF not between", value1, value2, "oiIdf");
            return (Criteria) this;
        }

        public Criteria andOiNameIsNull() {
            addCriterion("OI_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOiNameIsNotNull() {
            addCriterion("OI_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOiNameEqualTo(String value) {
            addCriterion("OI_NAME =", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameNotEqualTo(String value) {
            addCriterion("OI_NAME <>", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameGreaterThan(String value) {
            addCriterion("OI_NAME >", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameGreaterThanOrEqualTo(String value) {
            addCriterion("OI_NAME >=", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameLessThan(String value) {
            addCriterion("OI_NAME <", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameLessThanOrEqualTo(String value) {
            addCriterion("OI_NAME <=", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameLike(String value) {
            addCriterion("OI_NAME like", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameNotLike(String value) {
            addCriterion("OI_NAME not like", value, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameIn(List<String> values) {
            addCriterion("OI_NAME in", values, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameNotIn(List<String> values) {
            addCriterion("OI_NAME not in", values, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameBetween(String value1, String value2) {
            addCriterion("OI_NAME between", value1, value2, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiNameNotBetween(String value1, String value2) {
            addCriterion("OI_NAME not between", value1, value2, "oiName");
            return (Criteria) this;
        }

        public Criteria andOiTypeIsNull() {
            addCriterion("OI_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOiTypeIsNotNull() {
            addCriterion("OI_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOiTypeEqualTo(String value) {
            addCriterion("OI_TYPE =", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeNotEqualTo(String value) {
            addCriterion("OI_TYPE <>", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeGreaterThan(String value) {
            addCriterion("OI_TYPE >", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OI_TYPE >=", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeLessThan(String value) {
            addCriterion("OI_TYPE <", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeLessThanOrEqualTo(String value) {
            addCriterion("OI_TYPE <=", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeLike(String value) {
            addCriterion("OI_TYPE like", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeNotLike(String value) {
            addCriterion("OI_TYPE not like", value, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeIn(List<String> values) {
            addCriterion("OI_TYPE in", values, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeNotIn(List<String> values) {
            addCriterion("OI_TYPE not in", values, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeBetween(String value1, String value2) {
            addCriterion("OI_TYPE between", value1, value2, "oiType");
            return (Criteria) this;
        }

        public Criteria andOiTypeNotBetween(String value1, String value2) {
            addCriterion("OI_TYPE not between", value1, value2, "oiType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(String value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(String value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(String value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(String value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLike(String value) {
            addCriterion("DATA_TYPE like", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotLike(String value) {
            addCriterion("DATA_TYPE not like", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<String> values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<String> values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(String value1, String value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(String value1, String value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDatadatefIsNull() {
            addCriterion("DATADATEF is null");
            return (Criteria) this;
        }

        public Criteria andDatadatefIsNotNull() {
            addCriterion("DATADATEF is not null");
            return (Criteria) this;
        }

        public Criteria andDatadatefEqualTo(String value) {
            addCriterion("DATADATEF =", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotEqualTo(String value) {
            addCriterion("DATADATEF <>", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefGreaterThan(String value) {
            addCriterion("DATADATEF >", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefGreaterThanOrEqualTo(String value) {
            addCriterion("DATADATEF >=", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLessThan(String value) {
            addCriterion("DATADATEF <", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLessThanOrEqualTo(String value) {
            addCriterion("DATADATEF <=", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefLike(String value) {
            addCriterion("DATADATEF like", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotLike(String value) {
            addCriterion("DATADATEF not like", value, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefIn(List<String> values) {
            addCriterion("DATADATEF in", values, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotIn(List<String> values) {
            addCriterion("DATADATEF not in", values, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefBetween(String value1, String value2) {
            addCriterion("DATADATEF between", value1, value2, "datadatef");
            return (Criteria) this;
        }

        public Criteria andDatadatefNotBetween(String value1, String value2) {
            addCriterion("DATADATEF not between", value1, value2, "datadatef");
            return (Criteria) this;
        }

        public Criteria andAbasedataIsNull() {
            addCriterion("ABASEDATA is null");
            return (Criteria) this;
        }

        public Criteria andAbasedataIsNotNull() {
            addCriterion("ABASEDATA is not null");
            return (Criteria) this;
        }

        public Criteria andAbasedataEqualTo(String value) {
            addCriterion("ABASEDATA =", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataNotEqualTo(String value) {
            addCriterion("ABASEDATA <>", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataGreaterThan(String value) {
            addCriterion("ABASEDATA >", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataGreaterThanOrEqualTo(String value) {
            addCriterion("ABASEDATA >=", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataLessThan(String value) {
            addCriterion("ABASEDATA <", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataLessThanOrEqualTo(String value) {
            addCriterion("ABASEDATA <=", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataLike(String value) {
            addCriterion("ABASEDATA like", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataNotLike(String value) {
            addCriterion("ABASEDATA not like", value, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataIn(List<String> values) {
            addCriterion("ABASEDATA in", values, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataNotIn(List<String> values) {
            addCriterion("ABASEDATA not in", values, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataBetween(String value1, String value2) {
            addCriterion("ABASEDATA between", value1, value2, "abasedata");
            return (Criteria) this;
        }

        public Criteria andAbasedataNotBetween(String value1, String value2) {
            addCriterion("ABASEDATA not between", value1, value2, "abasedata");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNull() {
            addCriterion("JLSJ is null");
            return (Criteria) this;
        }

        public Criteria andJlsjIsNotNull() {
            addCriterion("JLSJ is not null");
            return (Criteria) this;
        }

        public Criteria andJlsjEqualTo(String value) {
            addCriterion("JLSJ =", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotEqualTo(String value) {
            addCriterion("JLSJ <>", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThan(String value) {
            addCriterion("JLSJ >", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjGreaterThanOrEqualTo(String value) {
            addCriterion("JLSJ >=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThan(String value) {
            addCriterion("JLSJ <", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLessThanOrEqualTo(String value) {
            addCriterion("JLSJ <=", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjLike(String value) {
            addCriterion("JLSJ like", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotLike(String value) {
            addCriterion("JLSJ not like", value, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjIn(List<String> values) {
            addCriterion("JLSJ in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotIn(List<String> values) {
            addCriterion("JLSJ not in", values, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjBetween(String value1, String value2) {
            addCriterion("JLSJ between", value1, value2, "jlsj");
            return (Criteria) this;
        }

        public Criteria andJlsjNotBetween(String value1, String value2) {
            addCriterion("JLSJ not between", value1, value2, "jlsj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUMFGPDATA2
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}