package com.dc.dlsb.dao;

import com.dc.dlsb.model.DmeDrcSumJzData;
import com.dc.dlsb.model.DmeDrcSumJzDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DmeDrcSumJzDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int countByExample(DmeDrcSumJzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int deleteByExample(DmeDrcSumJzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int insert(DmeDrcSumJzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int insertSelective(DmeDrcSumJzData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    List<DmeDrcSumJzData> selectByExample(DmeDrcSumJzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DmeDrcSumJzData record, @Param("example") DmeDrcSumJzDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DmeDrcSumJzData record, @Param("example") DmeDrcSumJzDataExample example);
}