package com.dc.dlsb.model;

import java.io.Serializable;

public class DmeDrcSumJzData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.JZBH
     *
     * @mbggenerated
     */
    private String jzbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.JZMC
     *
     * @mbggenerated
     */
    private String jzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.DATADATEF
     *
     * @mbggenerated
     */
    private String datadatef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.DATANUM
     *
     * @mbggenerated
     */
    private String datanum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.JLSJ
     *
     * @mbggenerated
     */
    private String jlsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUMJZDATA2.OI_IDF
     *
     * @mbggenerated
     */
    private String oiIdf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUMJZDATA2
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.JZBH
     *
     * @return the value of SUMJZDATA2.JZBH
     *
     * @mbggenerated
     */
    public String getJzbh() {
        return jzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.JZBH
     *
     * @param jzbh the value for SUMJZDATA2.JZBH
     *
     * @mbggenerated
     */
    public void setJzbh(String jzbh) {
        this.jzbh = jzbh == null ? null : jzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.JZMC
     *
     * @return the value of SUMJZDATA2.JZMC
     *
     * @mbggenerated
     */
    public String getJzmc() {
        return jzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.JZMC
     *
     * @param jzmc the value for SUMJZDATA2.JZMC
     *
     * @mbggenerated
     */
    public void setJzmc(String jzmc) {
        this.jzmc = jzmc == null ? null : jzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.DATADATEF
     *
     * @return the value of SUMJZDATA2.DATADATEF
     *
     * @mbggenerated
     */
    public String getDatadatef() {
        return datadatef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.DATADATEF
     *
     * @param datadatef the value for SUMJZDATA2.DATADATEF
     *
     * @mbggenerated
     */
    public void setDatadatef(String datadatef) {
        this.datadatef = datadatef == null ? null : datadatef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.DATANUM
     *
     * @return the value of SUMJZDATA2.DATANUM
     *
     * @mbggenerated
     */
    public String getDatanum() {
        return datanum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.DATANUM
     *
     * @param datanum the value for SUMJZDATA2.DATANUM
     *
     * @mbggenerated
     */
    public void setDatanum(String datanum) {
        this.datanum = datanum == null ? null : datanum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.JLSJ
     *
     * @return the value of SUMJZDATA2.JLSJ
     *
     * @mbggenerated
     */
    public String getJlsj() {
        return jlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.JLSJ
     *
     * @param jlsj the value for SUMJZDATA2.JLSJ
     *
     * @mbggenerated
     */
    public void setJlsj(String jlsj) {
        this.jlsj = jlsj == null ? null : jlsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUMJZDATA2.OI_IDF
     *
     * @return the value of SUMJZDATA2.OI_IDF
     *
     * @mbggenerated
     */
    public String getOiIdf() {
        return oiIdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUMJZDATA2.OI_IDF
     *
     * @param oiIdf the value for SUMJZDATA2.OI_IDF
     *
     * @mbggenerated
     */
    public void setOiIdf(String oiIdf) {
        this.oiIdf = oiIdf == null ? null : oiIdf.trim();
    }
}