package com.dc.dlsb.model;

import java.io.Serializable;

public class OmsJzglJzxx implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.JZBH
     *
     * @mbggenerated
     */
    private String jzbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.DCBH
     *
     * @mbggenerated
     */
    private String dcbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.JZMC
     *
     * @mbggenerated
     */
    private String jzmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.JZZT
     *
     * @mbggenerated
     */
    private String jzzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.ZJRL
     *
     * @mbggenerated
     */
    private String zjrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.XTZT
     *
     * @mbggenerated
     */
    private String xtzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.CJSJ
     *
     * @mbggenerated
     */
    private String cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.CZSJ
     *
     * @mbggenerated
     */
    private String czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.CZR
     *
     * @mbggenerated
     */
    private String czr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD1
     *
     * @mbggenerated
     */
    private String ylzd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD2
     *
     * @mbggenerated
     */
    private String ylzd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD3
     *
     * @mbggenerated
     */
    private String ylzd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD4
     *
     * @mbggenerated
     */
    private String ylzd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD5
     *
     * @mbggenerated
     */
    private String ylzd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD6
     *
     * @mbggenerated
     */
    private String ylzd6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD7
     *
     * @mbggenerated
     */
    private String ylzd7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD8
     *
     * @mbggenerated
     */
    private String ylzd8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD9
     *
     * @mbggenerated
     */
    private String ylzd9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JZGL_JZXX.YLZD10
     *
     * @mbggenerated
     */
    private String ylzd10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.JZBH
     *
     * @return the value of JZGL_JZXX.JZBH
     *
     * @mbggenerated
     */
    public String getJzbh() {
        return jzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.JZBH
     *
     * @param jzbh the value for JZGL_JZXX.JZBH
     *
     * @mbggenerated
     */
    public void setJzbh(String jzbh) {
        this.jzbh = jzbh == null ? null : jzbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.DCBH
     *
     * @return the value of JZGL_JZXX.DCBH
     *
     * @mbggenerated
     */
    public String getDcbh() {
        return dcbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.DCBH
     *
     * @param dcbh the value for JZGL_JZXX.DCBH
     *
     * @mbggenerated
     */
    public void setDcbh(String dcbh) {
        this.dcbh = dcbh == null ? null : dcbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.JZMC
     *
     * @return the value of JZGL_JZXX.JZMC
     *
     * @mbggenerated
     */
    public String getJzmc() {
        return jzmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.JZMC
     *
     * @param jzmc the value for JZGL_JZXX.JZMC
     *
     * @mbggenerated
     */
    public void setJzmc(String jzmc) {
        this.jzmc = jzmc == null ? null : jzmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.JZZT
     *
     * @return the value of JZGL_JZXX.JZZT
     *
     * @mbggenerated
     */
    public String getJzzt() {
        return jzzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.JZZT
     *
     * @param jzzt the value for JZGL_JZXX.JZZT
     *
     * @mbggenerated
     */
    public void setJzzt(String jzzt) {
        this.jzzt = jzzt == null ? null : jzzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.ZJRL
     *
     * @return the value of JZGL_JZXX.ZJRL
     *
     * @mbggenerated
     */
    public String getZjrl() {
        return zjrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.ZJRL
     *
     * @param zjrl the value for JZGL_JZXX.ZJRL
     *
     * @mbggenerated
     */
    public void setZjrl(String zjrl) {
        this.zjrl = zjrl == null ? null : zjrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.XTZT
     *
     * @return the value of JZGL_JZXX.XTZT
     *
     * @mbggenerated
     */
    public String getXtzt() {
        return xtzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.XTZT
     *
     * @param xtzt the value for JZGL_JZXX.XTZT
     *
     * @mbggenerated
     */
    public void setXtzt(String xtzt) {
        this.xtzt = xtzt == null ? null : xtzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.CJSJ
     *
     * @return the value of JZGL_JZXX.CJSJ
     *
     * @mbggenerated
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.CJSJ
     *
     * @param cjsj the value for JZGL_JZXX.CJSJ
     *
     * @mbggenerated
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj == null ? null : cjsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.CZSJ
     *
     * @return the value of JZGL_JZXX.CZSJ
     *
     * @mbggenerated
     */
    public String getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.CZSJ
     *
     * @param czsj the value for JZGL_JZXX.CZSJ
     *
     * @mbggenerated
     */
    public void setCzsj(String czsj) {
        this.czsj = czsj == null ? null : czsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.CZR
     *
     * @return the value of JZGL_JZXX.CZR
     *
     * @mbggenerated
     */
    public String getCzr() {
        return czr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.CZR
     *
     * @param czr the value for JZGL_JZXX.CZR
     *
     * @mbggenerated
     */
    public void setCzr(String czr) {
        this.czr = czr == null ? null : czr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD1
     *
     * @return the value of JZGL_JZXX.YLZD1
     *
     * @mbggenerated
     */
    public String getYlzd1() {
        return ylzd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD1
     *
     * @param ylzd1 the value for JZGL_JZXX.YLZD1
     *
     * @mbggenerated
     */
    public void setYlzd1(String ylzd1) {
        this.ylzd1 = ylzd1 == null ? null : ylzd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD2
     *
     * @return the value of JZGL_JZXX.YLZD2
     *
     * @mbggenerated
     */
    public String getYlzd2() {
        return ylzd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD2
     *
     * @param ylzd2 the value for JZGL_JZXX.YLZD2
     *
     * @mbggenerated
     */
    public void setYlzd2(String ylzd2) {
        this.ylzd2 = ylzd2 == null ? null : ylzd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD3
     *
     * @return the value of JZGL_JZXX.YLZD3
     *
     * @mbggenerated
     */
    public String getYlzd3() {
        return ylzd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD3
     *
     * @param ylzd3 the value for JZGL_JZXX.YLZD3
     *
     * @mbggenerated
     */
    public void setYlzd3(String ylzd3) {
        this.ylzd3 = ylzd3 == null ? null : ylzd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD4
     *
     * @return the value of JZGL_JZXX.YLZD4
     *
     * @mbggenerated
     */
    public String getYlzd4() {
        return ylzd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD4
     *
     * @param ylzd4 the value for JZGL_JZXX.YLZD4
     *
     * @mbggenerated
     */
    public void setYlzd4(String ylzd4) {
        this.ylzd4 = ylzd4 == null ? null : ylzd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD5
     *
     * @return the value of JZGL_JZXX.YLZD5
     *
     * @mbggenerated
     */
    public String getYlzd5() {
        return ylzd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD5
     *
     * @param ylzd5 the value for JZGL_JZXX.YLZD5
     *
     * @mbggenerated
     */
    public void setYlzd5(String ylzd5) {
        this.ylzd5 = ylzd5 == null ? null : ylzd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD6
     *
     * @return the value of JZGL_JZXX.YLZD6
     *
     * @mbggenerated
     */
    public String getYlzd6() {
        return ylzd6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD6
     *
     * @param ylzd6 the value for JZGL_JZXX.YLZD6
     *
     * @mbggenerated
     */
    public void setYlzd6(String ylzd6) {
        this.ylzd6 = ylzd6 == null ? null : ylzd6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD7
     *
     * @return the value of JZGL_JZXX.YLZD7
     *
     * @mbggenerated
     */
    public String getYlzd7() {
        return ylzd7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD7
     *
     * @param ylzd7 the value for JZGL_JZXX.YLZD7
     *
     * @mbggenerated
     */
    public void setYlzd7(String ylzd7) {
        this.ylzd7 = ylzd7 == null ? null : ylzd7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD8
     *
     * @return the value of JZGL_JZXX.YLZD8
     *
     * @mbggenerated
     */
    public String getYlzd8() {
        return ylzd8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD8
     *
     * @param ylzd8 the value for JZGL_JZXX.YLZD8
     *
     * @mbggenerated
     */
    public void setYlzd8(String ylzd8) {
        this.ylzd8 = ylzd8 == null ? null : ylzd8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD9
     *
     * @return the value of JZGL_JZXX.YLZD9
     *
     * @mbggenerated
     */
    public String getYlzd9() {
        return ylzd9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD9
     *
     * @param ylzd9 the value for JZGL_JZXX.YLZD9
     *
     * @mbggenerated
     */
    public void setYlzd9(String ylzd9) {
        this.ylzd9 = ylzd9 == null ? null : ylzd9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JZGL_JZXX.YLZD10
     *
     * @return the value of JZGL_JZXX.YLZD10
     *
     * @mbggenerated
     */
    public String getYlzd10() {
        return ylzd10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JZGL_JZXX.YLZD10
     *
     * @param ylzd10 the value for JZGL_JZXX.YLZD10
     *
     * @mbggenerated
     */
    public void setYlzd10(String ylzd10) {
        this.ylzd10 = ylzd10 == null ? null : ylzd10.trim();
    }
}