package com.dc.dlsb.model;

import java.util.ArrayList;
import java.util.List;

public class OmsJzglJzxxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public OmsJzglJzxxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJzbhIsNull() {
            addCriterion("JZBH is null");
            return (Criteria) this;
        }

        public Criteria andJzbhIsNotNull() {
            addCriterion("JZBH is not null");
            return (Criteria) this;
        }

        public Criteria andJzbhEqualTo(String value) {
            addCriterion("JZBH =", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotEqualTo(String value) {
            addCriterion("JZBH <>", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhGreaterThan(String value) {
            addCriterion("JZBH >", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhGreaterThanOrEqualTo(String value) {
            addCriterion("JZBH >=", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLessThan(String value) {
            addCriterion("JZBH <", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLessThanOrEqualTo(String value) {
            addCriterion("JZBH <=", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhLike(String value) {
            addCriterion("JZBH like", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotLike(String value) {
            addCriterion("JZBH not like", value, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhIn(List<String> values) {
            addCriterion("JZBH in", values, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotIn(List<String> values) {
            addCriterion("JZBH not in", values, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhBetween(String value1, String value2) {
            addCriterion("JZBH between", value1, value2, "jzbh");
            return (Criteria) this;
        }

        public Criteria andJzbhNotBetween(String value1, String value2) {
            addCriterion("JZBH not between", value1, value2, "jzbh");
            return (Criteria) this;
        }

        public Criteria andDcbhIsNull() {
            addCriterion("DCBH is null");
            return (Criteria) this;
        }

        public Criteria andDcbhIsNotNull() {
            addCriterion("DCBH is not null");
            return (Criteria) this;
        }

        public Criteria andDcbhEqualTo(String value) {
            addCriterion("DCBH =", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhNotEqualTo(String value) {
            addCriterion("DCBH <>", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhGreaterThan(String value) {
            addCriterion("DCBH >", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhGreaterThanOrEqualTo(String value) {
            addCriterion("DCBH >=", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhLessThan(String value) {
            addCriterion("DCBH <", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhLessThanOrEqualTo(String value) {
            addCriterion("DCBH <=", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhLike(String value) {
            addCriterion("DCBH like", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhNotLike(String value) {
            addCriterion("DCBH not like", value, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhIn(List<String> values) {
            addCriterion("DCBH in", values, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhNotIn(List<String> values) {
            addCriterion("DCBH not in", values, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhBetween(String value1, String value2) {
            addCriterion("DCBH between", value1, value2, "dcbh");
            return (Criteria) this;
        }

        public Criteria andDcbhNotBetween(String value1, String value2) {
            addCriterion("DCBH not between", value1, value2, "dcbh");
            return (Criteria) this;
        }

        public Criteria andJzmcIsNull() {
            addCriterion("JZMC is null");
            return (Criteria) this;
        }

        public Criteria andJzmcIsNotNull() {
            addCriterion("JZMC is not null");
            return (Criteria) this;
        }

        public Criteria andJzmcEqualTo(String value) {
            addCriterion("JZMC =", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotEqualTo(String value) {
            addCriterion("JZMC <>", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcGreaterThan(String value) {
            addCriterion("JZMC >", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcGreaterThanOrEqualTo(String value) {
            addCriterion("JZMC >=", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLessThan(String value) {
            addCriterion("JZMC <", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLessThanOrEqualTo(String value) {
            addCriterion("JZMC <=", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcLike(String value) {
            addCriterion("JZMC like", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotLike(String value) {
            addCriterion("JZMC not like", value, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcIn(List<String> values) {
            addCriterion("JZMC in", values, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotIn(List<String> values) {
            addCriterion("JZMC not in", values, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcBetween(String value1, String value2) {
            addCriterion("JZMC between", value1, value2, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzmcNotBetween(String value1, String value2) {
            addCriterion("JZMC not between", value1, value2, "jzmc");
            return (Criteria) this;
        }

        public Criteria andJzztIsNull() {
            addCriterion("JZZT is null");
            return (Criteria) this;
        }

        public Criteria andJzztIsNotNull() {
            addCriterion("JZZT is not null");
            return (Criteria) this;
        }

        public Criteria andJzztEqualTo(String value) {
            addCriterion("JZZT =", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztNotEqualTo(String value) {
            addCriterion("JZZT <>", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztGreaterThan(String value) {
            addCriterion("JZZT >", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztGreaterThanOrEqualTo(String value) {
            addCriterion("JZZT >=", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztLessThan(String value) {
            addCriterion("JZZT <", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztLessThanOrEqualTo(String value) {
            addCriterion("JZZT <=", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztLike(String value) {
            addCriterion("JZZT like", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztNotLike(String value) {
            addCriterion("JZZT not like", value, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztIn(List<String> values) {
            addCriterion("JZZT in", values, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztNotIn(List<String> values) {
            addCriterion("JZZT not in", values, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztBetween(String value1, String value2) {
            addCriterion("JZZT between", value1, value2, "jzzt");
            return (Criteria) this;
        }

        public Criteria andJzztNotBetween(String value1, String value2) {
            addCriterion("JZZT not between", value1, value2, "jzzt");
            return (Criteria) this;
        }

        public Criteria andZjrlIsNull() {
            addCriterion("ZJRL is null");
            return (Criteria) this;
        }

        public Criteria andZjrlIsNotNull() {
            addCriterion("ZJRL is not null");
            return (Criteria) this;
        }

        public Criteria andZjrlEqualTo(String value) {
            addCriterion("ZJRL =", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlNotEqualTo(String value) {
            addCriterion("ZJRL <>", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlGreaterThan(String value) {
            addCriterion("ZJRL >", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlGreaterThanOrEqualTo(String value) {
            addCriterion("ZJRL >=", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlLessThan(String value) {
            addCriterion("ZJRL <", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlLessThanOrEqualTo(String value) {
            addCriterion("ZJRL <=", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlLike(String value) {
            addCriterion("ZJRL like", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlNotLike(String value) {
            addCriterion("ZJRL not like", value, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlIn(List<String> values) {
            addCriterion("ZJRL in", values, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlNotIn(List<String> values) {
            addCriterion("ZJRL not in", values, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlBetween(String value1, String value2) {
            addCriterion("ZJRL between", value1, value2, "zjrl");
            return (Criteria) this;
        }

        public Criteria andZjrlNotBetween(String value1, String value2) {
            addCriterion("ZJRL not between", value1, value2, "zjrl");
            return (Criteria) this;
        }

        public Criteria andXtztIsNull() {
            addCriterion("XTZT is null");
            return (Criteria) this;
        }

        public Criteria andXtztIsNotNull() {
            addCriterion("XTZT is not null");
            return (Criteria) this;
        }

        public Criteria andXtztEqualTo(String value) {
            addCriterion("XTZT =", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztNotEqualTo(String value) {
            addCriterion("XTZT <>", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztGreaterThan(String value) {
            addCriterion("XTZT >", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztGreaterThanOrEqualTo(String value) {
            addCriterion("XTZT >=", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztLessThan(String value) {
            addCriterion("XTZT <", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztLessThanOrEqualTo(String value) {
            addCriterion("XTZT <=", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztLike(String value) {
            addCriterion("XTZT like", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztNotLike(String value) {
            addCriterion("XTZT not like", value, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztIn(List<String> values) {
            addCriterion("XTZT in", values, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztNotIn(List<String> values) {
            addCriterion("XTZT not in", values, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztBetween(String value1, String value2) {
            addCriterion("XTZT between", value1, value2, "xtzt");
            return (Criteria) this;
        }

        public Criteria andXtztNotBetween(String value1, String value2) {
            addCriterion("XTZT not between", value1, value2, "xtzt");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNull() {
            addCriterion("CJSJ is null");
            return (Criteria) this;
        }

        public Criteria andCjsjIsNotNull() {
            addCriterion("CJSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCjsjEqualTo(String value) {
            addCriterion("CJSJ =", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotEqualTo(String value) {
            addCriterion("CJSJ <>", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThan(String value) {
            addCriterion("CJSJ >", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjGreaterThanOrEqualTo(String value) {
            addCriterion("CJSJ >=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThan(String value) {
            addCriterion("CJSJ <", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLessThanOrEqualTo(String value) {
            addCriterion("CJSJ <=", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjLike(String value) {
            addCriterion("CJSJ like", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotLike(String value) {
            addCriterion("CJSJ not like", value, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjIn(List<String> values) {
            addCriterion("CJSJ in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotIn(List<String> values) {
            addCriterion("CJSJ not in", values, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjBetween(String value1, String value2) {
            addCriterion("CJSJ between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCjsjNotBetween(String value1, String value2) {
            addCriterion("CJSJ not between", value1, value2, "cjsj");
            return (Criteria) this;
        }

        public Criteria andCzsjIsNull() {
            addCriterion("CZSJ is null");
            return (Criteria) this;
        }

        public Criteria andCzsjIsNotNull() {
            addCriterion("CZSJ is not null");
            return (Criteria) this;
        }

        public Criteria andCzsjEqualTo(String value) {
            addCriterion("CZSJ =", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjNotEqualTo(String value) {
            addCriterion("CZSJ <>", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjGreaterThan(String value) {
            addCriterion("CZSJ >", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjGreaterThanOrEqualTo(String value) {
            addCriterion("CZSJ >=", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjLessThan(String value) {
            addCriterion("CZSJ <", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjLessThanOrEqualTo(String value) {
            addCriterion("CZSJ <=", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjLike(String value) {
            addCriterion("CZSJ like", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjNotLike(String value) {
            addCriterion("CZSJ not like", value, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjIn(List<String> values) {
            addCriterion("CZSJ in", values, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjNotIn(List<String> values) {
            addCriterion("CZSJ not in", values, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjBetween(String value1, String value2) {
            addCriterion("CZSJ between", value1, value2, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzsjNotBetween(String value1, String value2) {
            addCriterion("CZSJ not between", value1, value2, "czsj");
            return (Criteria) this;
        }

        public Criteria andCzrIsNull() {
            addCriterion("CZR is null");
            return (Criteria) this;
        }

        public Criteria andCzrIsNotNull() {
            addCriterion("CZR is not null");
            return (Criteria) this;
        }

        public Criteria andCzrEqualTo(String value) {
            addCriterion("CZR =", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrNotEqualTo(String value) {
            addCriterion("CZR <>", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrGreaterThan(String value) {
            addCriterion("CZR >", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrGreaterThanOrEqualTo(String value) {
            addCriterion("CZR >=", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrLessThan(String value) {
            addCriterion("CZR <", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrLessThanOrEqualTo(String value) {
            addCriterion("CZR <=", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrLike(String value) {
            addCriterion("CZR like", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrNotLike(String value) {
            addCriterion("CZR not like", value, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrIn(List<String> values) {
            addCriterion("CZR in", values, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrNotIn(List<String> values) {
            addCriterion("CZR not in", values, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrBetween(String value1, String value2) {
            addCriterion("CZR between", value1, value2, "czr");
            return (Criteria) this;
        }

        public Criteria andCzrNotBetween(String value1, String value2) {
            addCriterion("CZR not between", value1, value2, "czr");
            return (Criteria) this;
        }

        public Criteria andYlzd1IsNull() {
            addCriterion("YLZD1 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd1IsNotNull() {
            addCriterion("YLZD1 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd1EqualTo(String value) {
            addCriterion("YLZD1 =", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotEqualTo(String value) {
            addCriterion("YLZD1 <>", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1GreaterThan(String value) {
            addCriterion("YLZD1 >", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD1 >=", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1LessThan(String value) {
            addCriterion("YLZD1 <", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1LessThanOrEqualTo(String value) {
            addCriterion("YLZD1 <=", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1Like(String value) {
            addCriterion("YLZD1 like", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotLike(String value) {
            addCriterion("YLZD1 not like", value, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1In(List<String> values) {
            addCriterion("YLZD1 in", values, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotIn(List<String> values) {
            addCriterion("YLZD1 not in", values, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1Between(String value1, String value2) {
            addCriterion("YLZD1 between", value1, value2, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd1NotBetween(String value1, String value2) {
            addCriterion("YLZD1 not between", value1, value2, "ylzd1");
            return (Criteria) this;
        }

        public Criteria andYlzd2IsNull() {
            addCriterion("YLZD2 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd2IsNotNull() {
            addCriterion("YLZD2 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd2EqualTo(String value) {
            addCriterion("YLZD2 =", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotEqualTo(String value) {
            addCriterion("YLZD2 <>", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2GreaterThan(String value) {
            addCriterion("YLZD2 >", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD2 >=", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2LessThan(String value) {
            addCriterion("YLZD2 <", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2LessThanOrEqualTo(String value) {
            addCriterion("YLZD2 <=", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2Like(String value) {
            addCriterion("YLZD2 like", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotLike(String value) {
            addCriterion("YLZD2 not like", value, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2In(List<String> values) {
            addCriterion("YLZD2 in", values, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotIn(List<String> values) {
            addCriterion("YLZD2 not in", values, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2Between(String value1, String value2) {
            addCriterion("YLZD2 between", value1, value2, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd2NotBetween(String value1, String value2) {
            addCriterion("YLZD2 not between", value1, value2, "ylzd2");
            return (Criteria) this;
        }

        public Criteria andYlzd3IsNull() {
            addCriterion("YLZD3 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd3IsNotNull() {
            addCriterion("YLZD3 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd3EqualTo(String value) {
            addCriterion("YLZD3 =", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotEqualTo(String value) {
            addCriterion("YLZD3 <>", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3GreaterThan(String value) {
            addCriterion("YLZD3 >", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD3 >=", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3LessThan(String value) {
            addCriterion("YLZD3 <", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3LessThanOrEqualTo(String value) {
            addCriterion("YLZD3 <=", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3Like(String value) {
            addCriterion("YLZD3 like", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotLike(String value) {
            addCriterion("YLZD3 not like", value, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3In(List<String> values) {
            addCriterion("YLZD3 in", values, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotIn(List<String> values) {
            addCriterion("YLZD3 not in", values, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3Between(String value1, String value2) {
            addCriterion("YLZD3 between", value1, value2, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd3NotBetween(String value1, String value2) {
            addCriterion("YLZD3 not between", value1, value2, "ylzd3");
            return (Criteria) this;
        }

        public Criteria andYlzd4IsNull() {
            addCriterion("YLZD4 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd4IsNotNull() {
            addCriterion("YLZD4 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd4EqualTo(String value) {
            addCriterion("YLZD4 =", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4NotEqualTo(String value) {
            addCriterion("YLZD4 <>", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4GreaterThan(String value) {
            addCriterion("YLZD4 >", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD4 >=", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4LessThan(String value) {
            addCriterion("YLZD4 <", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4LessThanOrEqualTo(String value) {
            addCriterion("YLZD4 <=", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4Like(String value) {
            addCriterion("YLZD4 like", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4NotLike(String value) {
            addCriterion("YLZD4 not like", value, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4In(List<String> values) {
            addCriterion("YLZD4 in", values, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4NotIn(List<String> values) {
            addCriterion("YLZD4 not in", values, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4Between(String value1, String value2) {
            addCriterion("YLZD4 between", value1, value2, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd4NotBetween(String value1, String value2) {
            addCriterion("YLZD4 not between", value1, value2, "ylzd4");
            return (Criteria) this;
        }

        public Criteria andYlzd5IsNull() {
            addCriterion("YLZD5 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd5IsNotNull() {
            addCriterion("YLZD5 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd5EqualTo(String value) {
            addCriterion("YLZD5 =", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5NotEqualTo(String value) {
            addCriterion("YLZD5 <>", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5GreaterThan(String value) {
            addCriterion("YLZD5 >", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD5 >=", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5LessThan(String value) {
            addCriterion("YLZD5 <", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5LessThanOrEqualTo(String value) {
            addCriterion("YLZD5 <=", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5Like(String value) {
            addCriterion("YLZD5 like", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5NotLike(String value) {
            addCriterion("YLZD5 not like", value, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5In(List<String> values) {
            addCriterion("YLZD5 in", values, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5NotIn(List<String> values) {
            addCriterion("YLZD5 not in", values, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5Between(String value1, String value2) {
            addCriterion("YLZD5 between", value1, value2, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd5NotBetween(String value1, String value2) {
            addCriterion("YLZD5 not between", value1, value2, "ylzd5");
            return (Criteria) this;
        }

        public Criteria andYlzd6IsNull() {
            addCriterion("YLZD6 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd6IsNotNull() {
            addCriterion("YLZD6 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd6EqualTo(String value) {
            addCriterion("YLZD6 =", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6NotEqualTo(String value) {
            addCriterion("YLZD6 <>", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6GreaterThan(String value) {
            addCriterion("YLZD6 >", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD6 >=", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6LessThan(String value) {
            addCriterion("YLZD6 <", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6LessThanOrEqualTo(String value) {
            addCriterion("YLZD6 <=", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6Like(String value) {
            addCriterion("YLZD6 like", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6NotLike(String value) {
            addCriterion("YLZD6 not like", value, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6In(List<String> values) {
            addCriterion("YLZD6 in", values, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6NotIn(List<String> values) {
            addCriterion("YLZD6 not in", values, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6Between(String value1, String value2) {
            addCriterion("YLZD6 between", value1, value2, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd6NotBetween(String value1, String value2) {
            addCriterion("YLZD6 not between", value1, value2, "ylzd6");
            return (Criteria) this;
        }

        public Criteria andYlzd7IsNull() {
            addCriterion("YLZD7 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd7IsNotNull() {
            addCriterion("YLZD7 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd7EqualTo(String value) {
            addCriterion("YLZD7 =", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7NotEqualTo(String value) {
            addCriterion("YLZD7 <>", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7GreaterThan(String value) {
            addCriterion("YLZD7 >", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD7 >=", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7LessThan(String value) {
            addCriterion("YLZD7 <", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7LessThanOrEqualTo(String value) {
            addCriterion("YLZD7 <=", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7Like(String value) {
            addCriterion("YLZD7 like", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7NotLike(String value) {
            addCriterion("YLZD7 not like", value, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7In(List<String> values) {
            addCriterion("YLZD7 in", values, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7NotIn(List<String> values) {
            addCriterion("YLZD7 not in", values, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7Between(String value1, String value2) {
            addCriterion("YLZD7 between", value1, value2, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd7NotBetween(String value1, String value2) {
            addCriterion("YLZD7 not between", value1, value2, "ylzd7");
            return (Criteria) this;
        }

        public Criteria andYlzd8IsNull() {
            addCriterion("YLZD8 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd8IsNotNull() {
            addCriterion("YLZD8 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd8EqualTo(String value) {
            addCriterion("YLZD8 =", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8NotEqualTo(String value) {
            addCriterion("YLZD8 <>", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8GreaterThan(String value) {
            addCriterion("YLZD8 >", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD8 >=", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8LessThan(String value) {
            addCriterion("YLZD8 <", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8LessThanOrEqualTo(String value) {
            addCriterion("YLZD8 <=", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8Like(String value) {
            addCriterion("YLZD8 like", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8NotLike(String value) {
            addCriterion("YLZD8 not like", value, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8In(List<String> values) {
            addCriterion("YLZD8 in", values, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8NotIn(List<String> values) {
            addCriterion("YLZD8 not in", values, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8Between(String value1, String value2) {
            addCriterion("YLZD8 between", value1, value2, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd8NotBetween(String value1, String value2) {
            addCriterion("YLZD8 not between", value1, value2, "ylzd8");
            return (Criteria) this;
        }

        public Criteria andYlzd9IsNull() {
            addCriterion("YLZD9 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd9IsNotNull() {
            addCriterion("YLZD9 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd9EqualTo(String value) {
            addCriterion("YLZD9 =", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9NotEqualTo(String value) {
            addCriterion("YLZD9 <>", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9GreaterThan(String value) {
            addCriterion("YLZD9 >", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD9 >=", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9LessThan(String value) {
            addCriterion("YLZD9 <", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9LessThanOrEqualTo(String value) {
            addCriterion("YLZD9 <=", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9Like(String value) {
            addCriterion("YLZD9 like", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9NotLike(String value) {
            addCriterion("YLZD9 not like", value, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9In(List<String> values) {
            addCriterion("YLZD9 in", values, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9NotIn(List<String> values) {
            addCriterion("YLZD9 not in", values, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9Between(String value1, String value2) {
            addCriterion("YLZD9 between", value1, value2, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd9NotBetween(String value1, String value2) {
            addCriterion("YLZD9 not between", value1, value2, "ylzd9");
            return (Criteria) this;
        }

        public Criteria andYlzd10IsNull() {
            addCriterion("YLZD10 is null");
            return (Criteria) this;
        }

        public Criteria andYlzd10IsNotNull() {
            addCriterion("YLZD10 is not null");
            return (Criteria) this;
        }

        public Criteria andYlzd10EqualTo(String value) {
            addCriterion("YLZD10 =", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10NotEqualTo(String value) {
            addCriterion("YLZD10 <>", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10GreaterThan(String value) {
            addCriterion("YLZD10 >", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10GreaterThanOrEqualTo(String value) {
            addCriterion("YLZD10 >=", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10LessThan(String value) {
            addCriterion("YLZD10 <", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10LessThanOrEqualTo(String value) {
            addCriterion("YLZD10 <=", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10Like(String value) {
            addCriterion("YLZD10 like", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10NotLike(String value) {
            addCriterion("YLZD10 not like", value, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10In(List<String> values) {
            addCriterion("YLZD10 in", values, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10NotIn(List<String> values) {
            addCriterion("YLZD10 not in", values, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10Between(String value1, String value2) {
            addCriterion("YLZD10 between", value1, value2, "ylzd10");
            return (Criteria) this;
        }

        public Criteria andYlzd10NotBetween(String value1, String value2) {
            addCriterion("YLZD10 not between", value1, value2, "ylzd10");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JZGL_JZXX
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}